import Link from "next/link";
import { ArrowRight, BrainCircuit, LineChart, ShieldCheck } from "lucide-react";
import { Sparkline } from "@/components/sparkline";

export default function HomePage() {
  return <main className="landing">
    <nav className="landing-nav"><Link href="/" style={{ color: "inherit", textDecoration: "none" }}><div className="brand-lockup"><div className="brand-mark"><svg width="22" height="22" viewBox="0 0 96 96" fill="none"><path d="M19 51.5H31L37.5 34L48 64L56 43L61 51.5H77" stroke="#101211" strokeWidth="7" strokeLinecap="round" strokeLinejoin="round" /></svg></div><div><div className="brand-name">pulse</div><div className="brand-sub">market signal desk</div></div></div></Link><div className="landing-actions"><Link href="/login" className="ghost-button" style={{ textDecoration: "none" }}>Log in</Link><Link href="/signup" className="primary-button" style={{ textDecoration: "none" }}>Open workspace <ArrowRight size={13} style={{ display: "inline", verticalAlign: "-2px", marginLeft: 4 }} /></Link></div></nav>
    <section className="landing-hero"><div><div className="landing-kicker"><span />LIVE MARKET CONTEXT · BUILT FOR THE NEXT DECISION</div><h1>Watch the move.<br /><em>Read the why.</em></h1><p>Pulse turns your stock watchlist into a calm, real-time research desk — live quotes, stored price action, the news behind the move, and an AI read that tells you what matters next.</p><div className="landing-cta"><Link href="/dashboard" className="primary-button" style={{ textDecoration: "none", padding: "12px 16px" }}>Explore the demo <ArrowRight size={14} style={{ display: "inline", verticalAlign: "-2px", marginLeft: 5 }} /></Link><span className="landing-note">Demo data · no card required</span></div></div><div className="terminal-card"><div className="terminal-top"><span>pulse / overview</span><span className="terminal-lights"><span /><span /><span /></span></div><div className="terminal-body"><div className="terminal-metric"><div><div className="eyebrow" style={{ color: "#a5b1a5" }}>Lead signal · TSLA</div><strong>$437.11</strong></div><span>+2.05%</span></div><div className="terminal-chart"><Sparkline values={[425, 426, 424, 429, 431, 428, 435, 432, 438, 437, 441, 437]} large /></div><div className="terminal-rows"><div className="terminal-row"><strong>AAPL</strong><span>Services momentum</span><strong style={{ color: "#c6f135" }}>+1.26%</strong></div><div className="terminal-row"><strong>NVDA</strong><span>AI capex in focus</span><strong style={{ color: "#e7806d" }}>−0.82%</strong></div><div className="terminal-row"><strong>MSFT</strong><span>Azure remains resilient</span><strong style={{ color: "#c6f135" }}>+0.64%</strong></div></div></div></div></section>
    <section className="landing-features"><div className="feature"><div className="feature-index">01 / CONTEXT</div><h3><LineChart size={15} style={{ display: "inline", verticalAlign: "-3px", marginRight: 6 }} />Store the tape</h3><p>Snapshots turn a passing quote into a readable intraday line — your own source of price context.</p></div><div className="feature"><div className="feature-index">02 / SIGNAL</div><h3><BrainCircuit size={15} style={{ display: "inline", verticalAlign: "-3px", marginRight: 6 }} />Explain the move</h3><p>Structured AI insights connect metrics and headlines, with drivers, risks, and confidence in plain English.</p></div><div className="feature"><div className="feature-index">03 / TRUST</div><h3><ShieldCheck size={15} style={{ display: "inline", verticalAlign: "-3px", marginRight: 6 }} />Know the freshness</h3><p>Every quote carries a timestamp, every insight carries a disclaimer, and every refresh is observable.</p></div></section>
  </main>;
}
