import Link from "next/link";
import { Bell, ChevronLeft, LayoutDashboard, Search, Settings2, Sparkles, TrendingUp, Zap } from "lucide-react";
import type { DashboardPayload } from "@/lib/types";

function PulseMark({ compact = false }: { compact?: boolean }) {
  return <div className="brand-lockup"><div className="brand-mark" aria-hidden="true"><svg width="22" height="22" viewBox="0 0 96 96" fill="none"><path d="M19 51.5H31L37.5 34L48 64L56 43L61 51.5H77" stroke="#101211" strokeWidth="7" strokeLinecap="round" strokeLinejoin="round" /></svg></div>{!compact && <div><div className="brand-name">pulse</div><div className="brand-sub">market signal desk</div></div>}</div>;
}
function Sidebar({ provider }: { provider?: DashboardPayload["provider"] }) {
  const status = provider === "demo" ? "Demo mode" : provider === "finnhub" ? "Live market data" : "Provider setup needed";
  const detail = provider === "demo" ? "Fixtures are enabled explicitly with PULSE_DEMO_MODE=true." : provider === "finnhub" ? "Finnhub quotes, news, and profiles are connected." : "Add Finnhub and Groq keys to activate live research.";
  return <aside className="sidebar"><Link href="/" aria-label="Pulse home"><PulseMark /></Link><div><div className="nav-section-label">Workspace</div><nav className="nav-list"><Link href="/dashboard" className="nav-item active"><LayoutDashboard size={15} /><span>Overview</span></Link><Link href="/dashboard/AAPL" className="nav-item"><TrendingUp size={15} /><span>Signals</span><span className="nav-symbol">live</span></Link><button className="nav-item" disabled style={{ cursor: "not-allowed", opacity: 0.5 }} title="Coming soon"><Search size={15} /><span>Discover</span></button></nav></div><div><div className="nav-section-label">System</div><nav className="nav-list"><button className="nav-item" disabled style={{ cursor: "not-allowed", opacity: 0.5 }} title="Coming soon"><Bell size={15} /><span>Alerts</span></button><button className="nav-item" disabled style={{ cursor: "not-allowed", opacity: 0.5 }} title="Coming soon"><Settings2 size={15} /><span>Settings</span></button></nav></div><div className="sidebar-footer"><div className="demo-mini"><strong><Zap size={11} style={{ display: "inline", marginRight: 4 }} />{status}</strong><p>{detail}</p></div><div className="user-chip"><div className="avatar">JD</div><span>Pulse account</span></div></div></aside>;
}
export function AppShell({ children, detail = false, provider }: { children: React.ReactNode; detail?: boolean; provider?: DashboardPayload["provider"] }) { return <div className="shell-grid"><Sidebar provider={provider} /><div className="workspace"><header className="topbar"><div className="breadcrumb"><Link href="/dashboard" style={{ color: "inherit", textDecoration: "none" }}>Pulse</Link><ChevronLeft size={12} style={{ transform: "rotate(180deg)" }} /><strong>{detail ? "Symbol detail" : "Overview"}</strong></div><div className="topbar-actions"><span className="timestamp" style={{ color: "var(--ink-soft)", fontSize: 10 }}><Sparkles size={12} style={{ display: "inline", verticalAlign: "-2px", marginRight: 5 }} />AI-assisted research</span><button className="icon-button" aria-label="Notifications"><Bell size={15} /></button></div></header><main className="main-content">{children}</main></div></div>; }
